name: Publish Release

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'patch'

jobs:
  publish:
    name: Perform Publishing
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node.js 18.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.11
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: "3.11"

      - name: Install
        shell: bash
        run: |
          yarn global add node-gyp
          yarn --skip-integrity-check --network-timeout 100000
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      - name: Publish NPM
        # We need to retry the publish command in case of network errors.
        # Those errors are usually due to rate limiting on the NPM registry.
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          timeout_minutes: 5
          retry_wait_seconds: 30
          max_attempts: 3
          retry_on: error
          command: yarn publish:latest -- ${{ inputs.release_type }} && yarn publish:check
          on_retry_command: git reset --hard
        env:
          NPM_CONFIG_PROVENANCE: "true" # enable provenance check
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Get Actor User Data
        uses: octokit/request-action@21d174fc38ff59af9cf4d7e07347d29df6dbaa99 # v2.3.0
        id: actor_user_data
        with:
          route: GET /users/{user}
          user: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1
        with:
          path: packages/core

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          commiter: ${{ github.actor }} <${{ fromJson(steps.actor_user_data.outputs.data).email }}>
          author: ${{ github.actor }} <${{ fromJson(steps.actor_user_data.outputs.data).email }}>
          branch: bot/package-update
          title: Package update for version ${{ steps.package-version.outputs.current-version}}
          commit-message: Package update for version ${{ steps.package-version.outputs.current-version}}
          body: Automated package update for Theia version ${{ steps.package-version.outputs.current-version}}. Triggered by @${{ github.actor }}.
